### Register User

# @name registerAPI
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstname": "Ali",
  "lastname": "Bouali",
  "email":  "alibou@mail.com",
  "password": "password",
  "role":  "ADMIN"
}
###<{% client.global.set("auth-token", response.body.access_token);  %}
@authtoken={{registerAPI.response.body.token}}

### Testing
###GET http://localhost:8080/api/v1/testing-controller?jwtToken={{authtoken}}

### Query the Demo endpoint
GET http://localhost:8080/api/v1/demo-controller
Authorization: Bearer {{authtoken}}


### Change the password
PATCH http://localhost:8080/api/v1/users
Content-Type: application/json
Authorization: Bearer {{authtoken}}

{
  "currentPassword": "password",
  "newPassword": "newPassword",
  "confirmationPassword":  "newPassword"
}

### Login again and update the token
# @name newPasswordAuthenticate
POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json

{
  "email":  "alibou@mail.com",
  "password": "newPassword"
}

###> {% client.global.set("new-auth-token", response.body.access_token);  %}
@newAuthToken={{newPasswordAuthenticate.response.body.token}}

### Query the Demo endpoint after password change
GET http://localhost:8080/api/v1/demo-controller
Authorization: Bearer {{newAuthToken}}